version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: kubsu
      POSTGRES_USER: kubsu
      POSTGRES_PASSWORD: kubsu
    env_file:
      - .env
    ports:
      - 5432:5432
  
  service:
    container_name: dockerpost
    build: .
    ports: 
      - 8051:8051
    depends_on:
      - postgres
    command: ["sh", "-c", "uvicorn src.main:app --host 0.0.0.0 --port 8051"]
