name: Continous integration

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: eatdetey/dockerlab

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db-test:
        image: postgres:16
        env:
          POSTGRES_USER: kubsu
          POSTGRES_PASSWORD: kubsu
          POSTGRES_DB: kubsu
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Build test image
      run: |
        docker build \
          --build-arg TEST_PROFILE=true \
          -t ${{ env.IMAGE_NAME }}-test:latest .

    - name: Run tests
      run: |
        docker run --network host --rm \
          ${{ env.IMAGE_NAME }}-test:latest \
          sh -c "python -m pytest tests/"

  deploy:
    needs: test
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build production image
      run: |
        docker build \
          --build-arg TEST_PROFILE=false \
          -t ${{ env.IMAGE_NAME }}:latest .

    - name: Push to registry
      run: |
        docker push ${{ env.IMAGE_NAME }}:latest
